version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - .db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - C:\Localhost\wp_app\wp-content\plugins:/var/www/htmlwp-content/plugins
      - C:\Localhost\wp_app\wp-content\themes:/var/www/htmlwp-content/themes
      # - C:\Localhost\wp_app\:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}